'use client';
import { supabase } from '../lib/supabase';
import {useEffect,useMemo,useState} from 'react';
const base=[
 {title:'İlkbahar Gibi',author:'Beren Aksoy',cat:'Umut',text:'Rüzgârın taşıdığı her çiçek, yeniden doğuşun müjdesidir...',img:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=700&q=80'},
 {title:'Ay Işığında',author:'Kerem Bayraktar',cat:'Yalnızlık',text:'Ay, yine aynı yerde, ama bu gece daha yalnız...',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=80'},
 {title:'Sessiz Bir Veda',author:'Selin Karaca',cat:'Hüzün',text:'Bazı vedalar, kelimelere değil, sadece bakışlara yazılır...',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=80'},
 {title:'Yolculuk',author:'Alp Yılmaz',cat:'Doğa',text:'Her adımda biraz daha kendime yaklaşıyorum...',img:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=700&q=80'}
];
const cats=[['♥','Aşk'],['☁','Hüzün'],['♟','Yalnızlık'],['❧','Doğa'],['☼','Umut'],['⌛','Hayat'],['•••','Diğer']];
export default function Home(){
 const [poems,setPoems]=useState(base),[q,setQ]=useState(''),[cat,setCat]=useState(''),[modal,setModal]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem('siirhane-poems');if(saved)setPoems(JSON.parse(saved));}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('siirhane-poems',JSON.stringify(poems));}catch{}},[poems]);
 const [form,setForm]=useState({title:'',author:'',cat:'Aşk',text:''});
 const list=useMemo(()=>poems.filter(p=>(!q||(p.title+' '+p.author+' '+p.text).toLowerCase().includes(q.toLowerCase()))&&(!cat||p.cat===cat)),[poems,q,cat]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 const publish=e=>{e.preventDefault();setPoems([{...form,img:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=700&q=80'},...poems]);setForm({title:'',author:'',cat:'Aşk',text:''});setModal(false);notify('Şiirin başarıyla yayınlandı! ✨')};
 return <><header className="nav"><div className="logo"><div className="logo-mark">⌁</div><div><strong>Şiirhane</strong><small>Her şiir, yeni bir dünya...</small></div></div><a href="#ana">Ana Sayfa</a><a href="#siirler">Şiirler</a><a href="#kategoriler">Kategoriler</a><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Şiir veya şair ara..."/></div><button className="btn light" onClick={()=>setModal(true)}>Şiir Paylaş</button></header>
 <section className="hero" id="ana"><div><h1>Şiir, insanın<br/>kendisiyle konuşma biçimidir...</h1><p>Burada, her kelime bir duygunun izini taşır.<br/>Sen de kendi şiirini paylaş, bu güzel yolculukta bize katıl.</p><button className="btn light" onClick={()=>setModal(true)}>✒ Şiirini Paylaş</button></div><div className="quote">“En güzel şiirler,<br/>kalpten kalbe yazılanlardır...”</div></section>
 <main className="container"><div className="grid"><section><article className="card feature"><div><span className="label">★ Günün Şiiri</span><h2>Yalnızlık da Bir Yurt Gibi</h2><p className="excerpt">“Bazen insan, kalabalıkların içinde bile yalnızdır. Çünkü bazı yürekler, sadece kendini duyar...”</p><div className="meta">◉ Zeynep Arslan · 12 Nisan 2025</div><div className="actions"><button className="action" onClick={()=>notify('Şiir beğenilerine eklendi.')}>♥ 482</button><button className="action">♡ 76</button><button className="action" onClick={()=>notify('Şiir kaydedildi.')}>🔖</button><button className="action" onClick={()=>{navigator.clipboard?.writeText(location.href);notify('Şiir bağlantısı kopyalandı.')}}>↗</button></div></div><img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80" alt="Günün şiiri"/></article>
 <div className="section-head" id="kategoriler"><h2>⌁ Kategoriler</h2><small>Tüm Kategoriler →</small></div><div className="categories">{cats.map(([icon,name])=><button key={name} className={'category '+(cat===name?'active':'')} onClick={()=>setCat(cat===name?'':name)}><span>{icon}</span><small>{name}</small></button>)}</div>
 <div className="section-head" id="siirler"><h2>▤ En Yeni Şiirler</h2><small>{list.length} şiir</small></div><div className="poems">{list.map((p,i)=><article className="card poem" key={i}><img src={p.img} alt=""/><div className="poem-body"><small>{p.cat}</small><h3>{p.title}</h3><div className="meta">{p.author}</div><p>{p.text}</p><div className="actions"><button className="action" onClick={()=>notify('Şiir beğenilerine eklendi.')}>♥ {312-i*34}</button><button className="action" onClick={()=>notify('Şiir kaydedildi.')}>🔖</button></div></div></article>)}</div>{!list.length&&<div className="empty">Aramana uygun şiir bulunamadı.</div>}</section>
 <aside><div className="card side"><h3>♨ En Popüler Şiirler</h3>{[['Aşk Her Zaman Kazanır mı?','Elif Kaya · ♡ 1.2K'],['Biraz Hüzün, Biraz Umut','Mertcan Yıldız · ♡ 984'],['Doğanın Sessizliği','Nisanur Demir · ♡ 876'],['Kayıp Zamanlar','Emre Şahin · ♡ 742'],['Sen Gittin Ya...','Duru Çelik · ♡ 698']].map((x,i)=><div className="rank" key={x[0]}><span className="num">{i+1}</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div></div>)}</div><div className="card side quote-card"><h3>♧ Şiirden Alıntılar</h3><p>“Şiir, kelimelerin<br/>en güzel halidir.”</p></div><div className="callout"><div>Sen de şiirlerini paylaş,<br/>bu güzel topluluğun bir parçası ol.</div><br/><button className="btn light" onClick={()=>setModal(true)}>♙ Hemen Kayıt Ol</button></div></aside></div></main>
 <footer><div><div className="footer-logo">⌁ Şiirhane</div><small>Her şiir, yeni bir dünya...</small></div><div><small>Ana Sayfa · Şiirler · Yazarlar · Kategoriler · Hakkımızda · İletişim</small></div><div><small>© 2026 Şiirhane</small></div></footer>
 {modal&&<div className="modal" onClick={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal-box"><h2>Şiirini Paylaş ✍️</h2><form onSubmit={publish}><div className="field"><label>Şiir başlığı</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Şiirine bir isim ver..."/></div><div className="field"><label>Şair adı</label><input required value={form.author} onChange={e=>setForm({...form,author:e.target.value})} placeholder="Adın veya mahlasın..."/></div><div className="field"><label>Kategori</label><select value={form.cat} onChange={e=>setForm({...form,cat:e.target.value})}>{cats.map(x=><option key={x[1]}>{x[1]}</option>)}</select></div><div className="field"><label>Şiirin</label><textarea required value={form.text} onChange={e=>setForm({...form,text:e.target.value})} placeholder="Kelimelerini buraya bırak..."/></div><div className="modal-actions"><button type="button" className="btn light" onClick={()=>setModal(false)}>Vazgeç</button><button className="btn">Yayınla</button></div></form></div></div>}
 {toast&&<div className="toast">{toast}</div>}</>}
